---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-operator-http-jenkins-master
  namespace: jenkins
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`jenkins-172-24-133-52.traefik.me`)
    kind: Rule
    services:
    - name: jenkins-operator-http-jenkins-master
      port: 8080
