---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - jenkins-master-jenkins.yaml
resources:
  - ingress-route.yaml
  - middleware.yaml
secretGenerator:
  - name: traefik.me-ssl-certs
    namespace: jenkins
    files:
      - tls.crt
      - tls.key
    options:
      disableNameSuffixHash: true
  - name: jenkins-operator-api-github
    namespace: jenkins
    env: jenkins-operator-api-github.credentials
    options:
      disableNameSuffixHash: true
