---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - jenkins-operator-crd.yaml
  - jenkins-operator-rbac.yaml
  - jenkins-operator-deployment.yaml
  - jenkins-master-rbac.yaml
  - jenkins-master-jenkins.yaml
commonLabels:
    app.kubernetes.io/part-of: management
