---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-operator
  labels:
    app.kubernetes.io/name: jenkins-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    app.kubernetes.io/name: jenkins