name: "Test docker images"

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "master"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jayamorin
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Pull latest jenkins-master image and build
        run: |
          DATE_NOW="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          cd master
          docker pull jayamorin/jenkins-master:latest
          docker build -t jayamorin/jenkins-master:latest \
            --build-arg BUILD_DATE=${DATE_NOW} --build-arg BUILD_VERSION=${{ github.sha }} .
          docker inspect jayamorin/jenkins-master:latest
