name: "Test docker images"

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "master"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jayamorin
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Get current timedate
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Pull latest jenkins-master image and build
        env:
          NOW: ${{ steps.date.outputs.date }}
        run: |
          cd master
          docker pull jayamorin/jenkins-master:latest
          docker build -t jayamorin/jenkins-master:latest \
            --build-arg BUILD_DATE=${NOW} --build-arg BUILD_VERSION=${{ github.sha }} .
          docker inspect jayamorin/jenkins-master:latest

      - name: Pull latest jenkins-slave-python3.9 image and build
        env:
          NOW: ${{ steps.date.outputs.date }}
        run: |
          cd master
          docker pull jayamorin/jenkins-slave-python3.9:latest
          docker build -t jayamorin/jenkins-slave-python3.9:latest \
            --build-arg BUILD_DATE=${NOW} --build-arg BUILD_VERSION=${{ github.sha }} .
          docker inspect jenkins-slave-python3.9:latest
